services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: from-unknown-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/from-unknown
      - SPRING_REDIS_HOST=redis
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: from-unknown-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: from-unknown-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongo_data:
