spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/from-unknown}

  redis:
    url: ${SPRING_REDIS_URL}


logging:
  level:
    com.fromunknown.scheduler: INFO


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs